---
- name: Get info
  delegate_to: localhost
  register: collected_info
  somemodule.that.collects.info:

- name: Do something
  delegate_to: localhost
  loop: "{{ collected_info['some_list'] }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Debug
  register: _something_done
  somemodule.that.may.change.something:
